<a href="https://colab.research.google.com/github/santoshs0612/Foundational-Math-in-ML/blob/main/Intro_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas From basic to advance

In [2]:
import pandas as pd

pd_series_1 = pd.Series([1,2,3],index = ["Math", "Biology","CS"])

print(pd_series_1)
print(pd_series_1["Math"])
pd_dataframe_1 = pd.DataFrame({
    "student_name" : ["Santosh" ,"Bilok"],
    "math_score" : [75, 99],
    "biology_score" : [92, 95],
    "CS_score" : [88, 88],

})
print(pd_dataframe_1)
# print(pd_dataframe_1.head)
# print(pd_dataframe_1.tail)
# print(pd_dataframe_1.describe)
print(pd_dataframe_1.loc[0])
print(pd_dataframe_1.iloc[0])

Math       1
Biology    2
CS         3
dtype: int64
1
  student_name  math_score  biology_score  CS_score
0      Santosh          75             92        88
1        Bilok          99             95        88
student_name     Santosh
math_score            75
biology_score         92
CS_score              88
Name: 0, dtype: object
student_name     Santosh
math_score            75
biology_score         92
CS_score              88
Name: 0, dtype: object

In [3]:
pd_series2 = pd.Series([79,67,69],index = ["Math", "Biology","CS"])
# print(pd_series2)
# print(pd_series2[1])

dict1 = {"Math":79,"Biology":67,"CS":69}
pd_series3 = pd.Series(dict1)
# print(pd_series3['Math'])

pd_series4 = pd.Series([1,2,3,4,5])
pd_series5 = pd_series4 *2
pd_series6 = pd_series4 + 2
print(pd_series6)

0    3
1    4
2    5
3    6
4    7
dtype: int64

### DataFrame: Collection of Series

In [4]:
df1 = pd.DataFrame({
    'Name': ["Santosh", "Bilok", "Sweta"],
    "City" : ["Banglore", "Mumbai","Patna"],
    "Height": [5.9,6,5.5]
})
print(df1)
print(df1["Name"])

      Name      City  Height
0  Santosh  Banglore     5.9
1    Bilok    Mumbai     6.0
2    Sweta     Patna     5.5
0    Santosh
1      Bilok
2      Sweta
Name: Name, dtype: object

In [5]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
data_set = pd.read_csv(url)
print(data_set)
print(data_set.head())
print(data_set.tail())

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [6]:
# print(data_set.info())

In [7]:
# print(data_set.iloc[0])
# print(data_set.loc[0])
# print(data_set.iloc[149])
# print(data_set.loc[149])
print(data_set["species"])

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [8]:
print(data_set[(data_set["sepal_length"] > 6) & (data_set["species"]== "versicolor") & (data_set['petal_length'] <=1.8)])

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

In [9]:
data_set['Area of flower'] = data_set['sepal_length'] * data_set['sepal_width']
print(data_set.head())

   sepal_length  sepal_width  petal_length  petal_width species  \
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

   Area of flower
0           17.85
1           14.70
2           15.04
3           14.26
4           18.00

In [10]:
data_set.isnull().sum()

sepal_length      0
sepal_width       0
petal_length      0
petal_width       0
species           0
Area of flower    0
dtype: int64

In [11]:
data_set.groupby('species').mean()

,sepal_length,sepal_width,petal_length,petal_width,Area of flower
species,,,,,
setosa,5.006,3.428,1.462,0.246,17.2578
versicolor,5.936,2.770,4.260,1.326,16.5262
virginica,6.588,2.974,5.552,2.026,19.6846

In [12]:
data_set.groupby('species')['sepal_length'].agg('mean','max','min')

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepal_length, dtype: float64

In [13]:
data_set.sort_values(by='sepal_length',ascending=False)

,sepal_length,sepal_width,petal_length,petal_width,species,Area of flower
131,7.9,3.8,6.4,2.0,virginica,30.02
122,7.7,2.8,6.7,2.0,virginica,21.56
118,7.7,2.6,6.9,2.3,virginica,20.02
117,7.7,3.8,6.7,2.2,virginica,29.26
135,7.7,3.0,6.1,2.3,virginica,23.10
...,...,...,...,...,...,...
41,4.5,2.3,1.3,0.3,setosa,10.35
42,4.4,3.2,1.3,0.2,setosa,14.08
8,4.4,2.9,1.4,0.2,setosa,12.76
38,4.4,3.0,1.3,0.2,setosa,13.20
13,4.3,3.0,1.1,0.1,setosa,12.90

### Merging

In [20]:
df1 = pd.DataFrame({'id': [1,2,3], "Name": ["Santosh","Bilok","Sweta"]})
df2 = pd.DataFrame({'id': [1,2,3], "City": ["Banglore","Mumbai","Patna"]})
df3 = pd.DataFrame({'id': [4,25,6], "Name": ["Alice","Bob","Mariya"]})
# df3 = pd.merge(df1,df2,on='id')
# print(df3)

df4= pd.concat([df1,df3],ignore_index=False)
print(df4)

   id     Name
0   1  Santosh
1   2    Bilok
2   3    Sweta
0   4    Alice
1  25      Bob
2   6   Mariya

### Pandas Project

In [21]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
import pandas as pd
df = pd.read_csv(url)
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [23]:
# df.info()
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [24]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [27]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df.info()
df.drop(['Cabin'],axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

/tmp/ipykernel_435/1229306961.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

# Analyze survival Pattern
  - What is the overall survival rate?
  - What is the survival rate by gender?
  - What is the survival rate by passenger class(Pclasss)?
  - What is the average age of survival vs non-survivals?
  - What is the survival rate of children (Age<16) compared to adults?

In [28]:
df['Survived'].mean()*100

np.float64(38.38383838383838)

In [32]:
df.groupby('Sex')['Survived'].mean()*100

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [33]:
df.groupby('Pclass')['Survived'].mean()*100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [35]:
df.groupby('Survived')['Age'].mean()

Survived
0    30.415100
1    28.549778
Name: Age, dtype: float64

In [42]:
df[(df['Age']>16)]['Survived'].mean()*100
df[(df['Age']<16)]['Survived'].mean()*100

np.float64(59.036144578313255)

In [47]:
young = df[df['Survived']==1].sort_values(by='Age',ascending=True)
print(young['Name'])

803              Thomas, Master. Assad Alexander
755                    Hamalainen, Master. Viljo
644                       Baclini, Miss. Eugenie
469                Baclini, Miss. Helene Barbara
78                 Caldwell, Master. Alden Gates
                         ...
570                           Harris, Mr. George
829    Stone, Mrs. George Nelson (Martha Evelyn)
483                       Turkula, Mrs. (Hedwig)
275            Andrews, Miss. Kornelia Theodosia
630         Barkworth, Mr. Algernon Henry Wilson
Name: Name, Length: 342, dtype: object

In [50]:
bins = [0,16,60,float('inf')]
labels = ['Children','Adult','Senior']
df['Age_Group'] = pd.cut(df['Age'],bins=bins,labels=labels)
df.groupby('Age_Group')['Survived'].mean()*100

/tmp/ipykernel_435/1439138281.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Age_Group')['Survived'].mean()*100

Age_Group
Children    55.000000
Adult       36.671001
Senior      22.727273
Name: Survived, dtype: float64